[package]
name = "mdbook-numeq"
authors = ["Yannick Seurin"]
version = "0.5.0"
edition = "2021"
description = "An mdbook preprocessor for automatically numbering centered equations."
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/mdbook-numeq"
homepage = "https://github.com/yannickseurin/mdbook-numeq"
repository = "https://github.com/yannickseurin/mdbook-numeq"
keywords = ["mdbook", "preprocessor", "katex"]

[dependencies]
clap = { version = "4.5.53", features = ["cargo"] }
tracing = "0.1.44"
tracing-subscriber = {version = "0.3.22", features = ["env-filter"]}
lazy_static = "1.5.0"
log = "0.4.29"
mdbook-preprocessor = "0.5.2"
pathdiff = "0.2.3"
regex = "1.12.2"
semver = "1.0.27"
serde_json = "1.0.145"
toml = "0.9.8"
